# è‡ªåŠ¨æ‰¹å‡† PR å’Œ Qodana æ£€æŸ¥çš„ GitHub Actions å·¥ä½œæµ
name: Auto Approve and Qodana Check

on:
  pull_request_target:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*' # é€‚ç”¨äºå‘å¸ƒåˆ†æ”¯

jobs:
  qodana-check:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      # æ£€å‡ºä»£ç 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # æ£€å‡º PR çš„å®é™…æäº¤
          fetch-depth: 0

      # è¿è¡Œ Qodana æ‰«æ
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

  gradle-build:
    runs-on: ubuntu-latest
    steps:
      # æ£€å‡ºä»£ç 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # æ£€å‡º PR çš„å®é™…æäº¤
          fetch-depth: 0 # æ‹‰å–å®Œæ•´çš„æäº¤å†å²

      # è®¾ç½® JDK 23 ç¯å¢ƒ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # ä½¿ç”¨æœ€æ–°çš„ v4 ç‰ˆæœ¬

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Verify Java installation
        run: java -version

      - name: check bash
        run: bash --version

      - name: Build with Gradle
        run: bash gradlew build # ä½¿ç”¨ Gradle æ„å»ºé¡¹ç›®

      # ä¸Šä¼ æ„å»ºç”Ÿæˆçš„å·¥ä»¶ï¼ˆartifactï¼‰
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xyz.tzpro.Zephyr # å·¥ä»¶åç§°
          path: build/libs # æŒ‡å®šæ„å»ºäº§ç‰©è·¯å¾„

  auto-approve:
    # åªæœ‰åœ¨ Qodana æ£€æŸ¥æˆåŠŸæ—¶æ‰è¿è¡Œè‡ªåŠ¨æ‰¹å‡†
    needs:
      - qodana-check
      - gradle-build
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' || github.actor == 'binaryYuki' || github.actor == 'Austin-152'
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          review-message: "It seems your pr has passed all tests. I'll approve it for you! ğŸš€"

