# è‡ªåŠ¨æ‰¹å‡† PR å’Œ Qodana æ£€æŸ¥çš„ GitHub Actions å·¥ä½œæµ
name: Auto Approve and Qodana Check

on:
  pull_request_target:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'releases/*' # é€‚ç”¨äºå‘å¸ƒåˆ†æ”¯

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      # æ£€å‡ºä»£ç 
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # æ£€å‡º PR çš„å®é™…æäº¤
          fetch-depth: 0

      # è¿è¡Œ Qodana æ‰«æ
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

  auto-approve:
    # åªæœ‰åœ¨ Qodana æ£€æŸ¥æˆåŠŸæ—¶æ‰è¿è¡Œè‡ªåŠ¨æ‰¹å‡†
    needs: qodana-check
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' || github.actor == 'binaryYuki' || github.actor == 'Austin-152'
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          review-message: "It seems like this PR doesn't need a review. I'll approve it for you! ğŸš€"
